In [2]:
from array import *
import numpy as np
import pandas as pd
# l=list[1,2,3,4,5]

# Create different data structures
arr = array('i', [1, 2, 3, 4, 5])
l = [1, 2, 3, 4, 5]

# NumPy arrays (kept all versions, different names)
a_1d = np.array([1, 2, 3, 4, 5])            # original 1D array 
a_2d = np.array([[1, 2, 3],
                 [3, 4, 5],
                 [5, 6, 7]])                 # 2D array
a_arange = np.arange(1, 7).reshape((2, 3))

s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                   'B': [6, 7, 8, 9, 10]},
                  index=['a', 'b', 'c', 'd', 'e'])

# Print results for each type with clear labels
print("=== Python array.array ===")
print("Original:", arr)
print("After *2 :", arr * 2)
print("-" * 60)

print("=== Python list ===")
print("Original:", l)
print("After *2 :", l * 2)
print("-" * 60)

print("=== NumPy 1D array (a_1d) ===")
print("Original:", a_1d)
print("After *2:", a_1d * 2)
print("shape:", a_1d.shape, "dtype:", a_1d.dtype)
print("-" * 60)

print("=== NumPy 2D array (a_2d) ===")
print("Original:\n", a_2d)
print("After *2:\n", a_2d * 2)
print("shape:", a_2d.shape, "dtype:", a_2d.dtype)
print("-" * 60)

print("=== NumPy array from arange (a_arange) ===")
print("Original:\n", a_arange)
print("After *2:\n", a_arange * 2)
print("shape:", a_arange.shape, "dtype:", a_arange.dtype)
print("-" * 60)

print("=== pandas Series ===")
print("Original:\n", s)
print("After *2:\n", s * 2)
print("-" * 60)

print("=== pandas DataFrame ===")
print("Original:\n", df)
print("After *2:\n", df * 2)
print("-" * 60)

=== Python array.array ===
Original: array('i', [1, 2, 3, 4, 5])
After *2 : array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 5])
------------------------------------------------------------
=== Python list ===
Original: [1, 2, 3, 4, 5]
After *2 : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
------------------------------------------------------------
=== NumPy 1D array (a_1d) ===
Original: [1 2 3 4 5]
After *2: [ 2  4  6  8 10]
shape: (5,) dtype: int32
------------------------------------------------------------
=== NumPy 2D array (a_2d) ===
Original:
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
After *2:
 [[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]
shape: (3, 3) dtype: int32
------------------------------------------------------------
=== NumPy array from arange (a_arange) ===
Original:
 [[1 2 3]
 [4 5 6]]
After *2:
 [[ 2  4  6]
 [ 8 10 12]]
shape: (2, 3) dtype: int32
------------------------------------------------------------
=== pandas Series ===
Original:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
After *2:
 a     2
b   

| Concept              | Dimension | Origin                      | Operation Behavior                                 | Example  | Result                                          |
| -------------------- | --------- | --------------------------- | -------------------------------------------------- | -------- | ----------------------------------------------- |
| **NumPy 1D array**   | 1D        | Native to NumPy             | Element-wise operation                             | `a * 2`  | Each element is multiplied by 2                 |
| **NumPy 2D array**   | 2D        | Native to NumPy             | Element-wise operation across all rows and columns | `a2 * 2` | Each element in the 2D array is multiplied by 2 |
| **Pandas Series**    | 1D        | Built on top of NumPy       | Element-wise operation                             | `df['Price'] > 10` | Each element is compared with 10                |
| **Pandas DataFrame** | 2D        | Composed of multiple Series | Element-wise operation by column                   | `df * 2` | Each element in all columns is multiplied by 2  |

    Any arithmetic or comparison on a Pandas column is element-wise — inherited from NumPy’s array operations

**Pandas Data Selection Cheat Sheet**
| Purpose                                         | Syntax                                          | Example                      | Return Type                                |
| ----------------------------------------------- | ----------------------------------------------- | ---------------------------- | ------------------------------------------ |
| Select **one row** by label                     | `df.loc['label']`                               | `df.loc['a']`                | `Series`                                   |
| Select **multiple rows** by labels              | `df.loc[['label1','label2']]`                   | `df.loc[['a','b']]`          | `DataFrame`                                |
| Select rows by **condition**                    | `df.loc[df['column'] > value]`                  | `df.loc[df['A'] > 5]`        | `DataFrame`                                |
| Select **specific columns**                     | `df[['col1','col2']]`                           | `df[['name','age']]`         | `DataFrame`                                |
| Select rows by condition **and** choose columns | `df.loc[df['column'] > value, ['col2']]`        | `df.loc[df['A'] > 5, ['B']]` | `DataFrame`                                |
| Select by **row and column position**           | `df.iloc[row_start:row_end, col_start:col_end]` | `df.iloc[0:2, 1:3]`          | `DataFrame`                                |
| Select a **single cell (row + column)**         | `df.loc['label', 'column']`                     | `df.loc['a', 'A']`           | scalar value (`int`, `float`, `str`, etc.) |

.loc[] → label-based indexing (use row/column names)

.iloc[] → position-based indexing (use integer indexes)

**Single row → returns a Series**
| Type                         | Example / Structure                                                                      | Index                            | Values             | How to access / Indexing                                                       |
| ---------------------------- | ---------------------------------------------------------------------------------------- | -------------------------------- | ------------------ | ------------------------------------------------------------------------------ |
| **1D array (list/np.array)** | `[ '2025-01-01', 10 ]`                                                                   | 0, 1, …                          | `'2025-01-01', 10` | `arr[0] → '2025-01-01'`<br>`arr[1] → 10`                                       |
| **Series (from DataFrame)**  | `Index: a`<br>`Date     2025-01-01`<br>`Price            10`<br>`Name: a, dtype: object` | `'Date', 'Price'` (column names) | `'2025-01-01', 10` | `row['Date'] → '2025-01-01'`<br>`row['Price'] → 10`<br>`row[0] → '2025-01-01'` |


**Multiple rows or columns → returns a DataFrame**

Single cell → returns a scalar value

**NumPy Indexing and Slicing Cheat Sheet**
| Purpose                                 | Syntax                                    | Example        | Return Type                   |
| --------------------------------------- | ----------------------------------------- | -------------- | ----------------------------- |
| Select the **1st row**                  | `a[row]`                                  | `a[0]`         | 1D array                      |
| Select the **2nd column**               | `a[:, column]`                            | `a[:, 1]`      | 1D array                      |
| Select a **single element**             | `a[row, column]`                          | `a[1, 2]`      | scalar (`int`, `float`, etc.) |
| Select a **range of rows and columns**  | `a[row_start:row_end, col_start:col_end]` | `a[0:2, 0:2]`  | 2D array                      |
| Select **specific rows**                | `a[[row1, row2], :]`                      | `a[[0, 2], :]` | 2D array                      |
| Select a **column and apply operation** | `a[:, column] * 2`                        | `a[:, 1] * 2`  | 1D array                      |
| Select elements by **condition**        | `a[condition]`                            | `a[a > 50]`    | 1D array (flattened)          |